export const toDoData = [
  {
    id: 0,
    title: "Weekly Bigbazar Shopping",
    status: "pending",
    badge: "In Progress",
    badgeclass: "badge-light-primary",
    timelimit: "10 Nov",
  },
  {
    id: 1,
    title: "Go Outside Picnic on Sunday",
    status: "pending",
    badge: "Pending",
    badgeclass: "badge-light-danger",
    timelimit: "04 Aug",
  },
  {
    id: 2,
    title: "Write a blog post",
    status: "completed",
    badge: "Done",
    badgeclass: "badge-light-success",
    timelimit: "25 Feb",
  },
  {
    id: 3,
    title: "Do the chicken dance",
    status: "pending",
    badge: "In Progress",
    badgeclass: "badge-light-primary",
    timelimit: "15 Dec",
  },
  {
    id: 4,
    title: "Pay the electricity bills",
    status: "pending",
    badge: "Pending",
    badgeclass: "badge-light-danger",
    timelimit: "11 Nov",
  },
  {
    id: 5,
    title: "Make dinner reservation",
    status: "completed",
    badge: "Done",
    badgeclass: "badge-light-success",
    timelimit: "08 July",
  },
  {
    id: 6,
    title: "Meeting with photographer",
    status: "completed",
    badge: "Done",
    badgeclass: "badge-light-success",
    timelimit: "08 Sep",
  },
  {
    id: 7,
    title: "Birthday wish to best friend",
    status: "completed",
    badge: "Done",
    badgeclass: "badge-light-success",
    timelimit: "08 Sep",
  },
];
